// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: kq/kq.proto

package kq

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// next id: 13
type TaskEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// stable unique identifier of the task
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// type of the task that needs to be performed
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// data required to perform the task
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// original enqueue time of the task
	EnqueuedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=enqueued_at,json=enqueuedAt,proto3" json:"enqueued_at,omitempty"`
	// max number of retries of the task
	Retries int32 `protobuf:"varint,5,opt,name=retries,proto3" json:"retries,omitempty"`
	// current number of retries of the task
	Retried int32 `protobuf:"varint,6,opt,name=retried,proto3" json:"retried,omitempty"`
	// minimum delay after the retry record's broker append timestamp (for the current retry)
	RetryAfter *durationpb.Duration `protobuf:"bytes,7,opt,name=retry_after,json=retryAfter,proto3" json:"retry_after,omitempty"`
	// the amount of time in which the task can execute (per attempt)
	Timeout *durationpb.Duration `protobuf:"bytes,8,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// the latest time at which the task can execute (across all attempts)
	Deadline *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=deadline,proto3" json:"deadline,omitempty"`
	// error message of the last failure of the task
	LastError string `protobuf:"bytes,10,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	// timestamp of the error of the task
	LastErrorAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_error_at,json=lastErrorAt,proto3" json:"last_error_at,omitempty"`
	// arbitrary metadata of a task
	Metadata      map[string]string `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskEnvelope) Reset() {
	*x = TaskEnvelope{}
	mi := &file_kq_kq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEnvelope) ProtoMessage() {}

func (x *TaskEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_kq_kq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEnvelope.ProtoReflect.Descriptor instead.
func (*TaskEnvelope) Descriptor() ([]byte, []int) {
	return file_kq_kq_proto_rawDescGZIP(), []int{0}
}

func (x *TaskEnvelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskEnvelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TaskEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TaskEnvelope) GetEnqueuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EnqueuedAt
	}
	return nil
}

func (x *TaskEnvelope) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

func (x *TaskEnvelope) GetRetried() int32 {
	if x != nil {
		return x.Retried
	}
	return 0
}

func (x *TaskEnvelope) GetRetryAfter() *durationpb.Duration {
	if x != nil {
		return x.RetryAfter
	}
	return nil
}

func (x *TaskEnvelope) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *TaskEnvelope) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *TaskEnvelope) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *TaskEnvelope) GetLastErrorAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastErrorAt
	}
	return nil
}

func (x *TaskEnvelope) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_kq_kq_proto protoreflect.FileDescriptor

const file_kq_kq_proto_rawDesc = "" +
	"\n" +
	"\vkq/kq.proto\x12\x02kq\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbe\x04\n" +
	"\fTaskEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12;\n" +
	"\venqueued_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"enqueuedAt\x12\x18\n" +
	"\aretries\x18\x05 \x01(\x05R\aretries\x12\x18\n" +
	"\aretried\x18\x06 \x01(\x05R\aretried\x12:\n" +
	"\vretry_after\x18\a \x01(\v2\x19.google.protobuf.DurationR\n" +
	"retryAfter\x123\n" +
	"\atimeout\x18\b \x01(\v2\x19.google.protobuf.DurationR\atimeout\x126\n" +
	"\bdeadline\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12\x1d\n" +
	"\n" +
	"last_error\x18\n" +
	" \x01(\tR\tlastError\x12>\n" +
	"\rlast_error_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vlastErrorAt\x12:\n" +
	"\bmetadata\x18\f \x03(\v2\x1e.kq.TaskEnvelope.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B+Z)github.com/raydatray/kq/internal/proto/kqb\x06proto3"

var (
	file_kq_kq_proto_rawDescOnce sync.Once
	file_kq_kq_proto_rawDescData []byte
)

func file_kq_kq_proto_rawDescGZIP() []byte {
	file_kq_kq_proto_rawDescOnce.Do(func() {
		file_kq_kq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kq_kq_proto_rawDesc), len(file_kq_kq_proto_rawDesc)))
	})
	return file_kq_kq_proto_rawDescData
}

var file_kq_kq_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kq_kq_proto_goTypes = []any{
	(*TaskEnvelope)(nil),          // 0: kq.TaskEnvelope
	nil,                           // 1: kq.TaskEnvelope.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 3: google.protobuf.Duration
}
var file_kq_kq_proto_depIdxs = []int32{
	2, // 0: kq.TaskEnvelope.enqueued_at:type_name -> google.protobuf.Timestamp
	3, // 1: kq.TaskEnvelope.retry_after:type_name -> google.protobuf.Duration
	3, // 2: kq.TaskEnvelope.timeout:type_name -> google.protobuf.Duration
	2, // 3: kq.TaskEnvelope.deadline:type_name -> google.protobuf.Timestamp
	2, // 4: kq.TaskEnvelope.last_error_at:type_name -> google.protobuf.Timestamp
	1, // 5: kq.TaskEnvelope.metadata:type_name -> kq.TaskEnvelope.MetadataEntry
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_kq_kq_proto_init() }
func file_kq_kq_proto_init() {
	if File_kq_kq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kq_kq_proto_rawDesc), len(file_kq_kq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kq_kq_proto_goTypes,
		DependencyIndexes: file_kq_kq_proto_depIdxs,
		MessageInfos:      file_kq_kq_proto_msgTypes,
	}.Build()
	File_kq_kq_proto = out.File
	file_kq_kq_proto_goTypes = nil
	file_kq_kq_proto_depIdxs = nil
}
