syntax = "proto3";

package kq;

import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/raydatray/kq/internal/proto/kq";

// next id: 12
message TaskEnvelope {
  // stable unique identifier of the task
  string id = 1;

  // type of the task that needs to be performed
  string type = 2;

  // data required to perform the task
  bytes payload = 3;

  // original enqueue time of the task
  google.protobuf.Timestamp enqueued_at = 4;

  // max number of retries of the task
  int32 retries = 5;

  // current number of retries of the task
  int32 retried = 6;

  // the amount of time in which the task can execute (per attempt)
  google.protobuf.Duration timeout = 7;

  // the latest time at which the task can execute (across all attempts)
  google.protobuf.Timestamp deadline = 8;

  // error message of the last failure of the task
  string last_error = 9;

  // timestamp of the error of the task
  google.protobuf.Timestamp last_error_at = 10;

  // arbitrary metadata of a task
  map<string, string> metadata = 11;
}
